<a href="https://colab.research.google.com/github/AhmetA75/TASK10_A/blob/main/TASK10_A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from time import time
import warnings as warn

In [8]:
data= pd.read_excel('Temporary_data3_Left_Right_Copy.xlsx')

In [24]:
y = data['CDRGLOB']
X = data.drop('CDRGLOB', axis=1)

In [30]:
X

SEX  EDUC  MARISTAT  INDEPEND  RESIDENC  NACCFAM  ANYMEDS  SMOKYRS  \
0       2    18         1         1         1        1        1        0   
1       1    11         1         1         1        1        1        0   
2       2    16         1         1         1        1        1       10   
3       1    14         1         1         1        0        1        0   
4       1    16         1         1         2        0        1       50   
...   ...   ...       ...       ...       ...      ...      ...      ...   
1349    1    20         1         1         1        1        1        0   
1350    1    16         1         2         1        0        1        0   
1351    2    14         2         1         1        1        1        0   
1352    2    20         3         1         1        1        1       25   
1353    2    14         1         1         1        1        1       10   

      NACCTBI  DIABETES  ...   RSUPFR  RSUPFRM  RSUPPAR  RSUPPARM  RSUPTEM  \
0           0         0  ...  27.9038   2.2157  10.3481    1.7014  13.4250   
1           0         0  ...  29.0600   2.6900   9.2500    1.6300  14.8800   
2           0         1  ...  33.0000   2.5400  13.6900    1.5600  16.2300   
3           0         1  ...  31.6800   2.4100   9.6400    1.4500  15.1100   
4           0         0  ...  28.0631   1.9501   9.1125    1.0427  13.3763   
...       ...       ...  ...      ...      ...      ...       ...      ...   
1349        0         0  ...  24.6892   2.6528  10.5460    2.1712  14.1128   
1350        0         0  ...  24.7908   2.0993  10.4094    1.4855  10.7880   
1351        0         0  ...  23.8500   2.1200  12.3900    1.5300  12.6600   
1352        0         0  ...  31.3500   2.4300  10.8200    1.7000  13.7700   
1353        0         0  ...  21.9900   2.4100   9.8900    1.7600  13.9600   

      RSUPTEMM  RSUPMAR  RSUPMARM  RTRTEM  RTRTEMM  
0       1.7419   9.8700    1.6792  0.8906   1.1947  
1       2.3000   7.2700    1.8900  1.3800   2.0300  
2       2.0700  10.1100    1.8400  1.0100   1.5000  
3       1.6400  10.3900    1.8300  0.7400   1.1000  
4       1.6270   7.5844    1.4595  0.6638   0.8527  
...        ...      ...       ...     ...      ...  
1349    2.8833   9.3176    2.3582  0.6735   1.0270  
1350    1.9027  10.2034    2.0484  0.7267   0.7946  
1351    1.9900   9.4800    1.7400  1.1800   1.5900  
1352    2.1000  11.1200    2.1400  1.3100   1.5200  
1353    2.2000   9.9600    1.8600  0.8300   1.6500  

[1354 rows x 185 columns]

In [31]:
#data.head(100)

In [32]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.25, stratify=y)

In [33]:
decision_tree = DecisionTreeClassifier()  
random_forest = RandomForestClassifier()
SVC = svm.LinearSVC()

In [34]:
decision_tree.fit(X=x_train, y=y_train) #Classified Features
random_forest.fit(X=x_train, y=y_train)
SVC.fit(X=x_train, y=y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,


LinearSVC()

In [37]:
print(f'TEST ACC DT ==> {decision_tree.score(x_test, y_test)}') 
print(f'TEST ACC RF ==> {random_forest.score(x_test, y_test)}')
print(f'TEST ACC SVC ==> {SVC.score(x_test, y_test)}')

TEST ACC DT ==> 0.6047197640117994
TEST ACC RF ==> 0.6607669616519174
TEST ACC SVC ==> 0.5339233038348082


In [45]:
warn.simplefilter('ignore')

In [39]:
decision_tree_param = {
                    'criterion' : ['chi','gini'],
                    'min_samples_split': [2,4],
                    'min_samples_leaf' : [1,2,3,4,5],
                    'random_state': [22],
                    'ccp_alpha': [0.1 ,0.2, 0.5]}

In [60]:
random_forest_param = {
                    'n_estimators' : [10,20,50,100],
                    'criterion' : ['chi','gini'],
                    'min_samples_split': [2,4,6],
                    'min_weight_fraction_leaf' : [0.001,0.1,0.2,0.3],
                    'verbose' :[0],
                    'random_state': [22],
                    'ccp_alpha': [0.1 ,0.2, 0.5],
                    'max_depth': [1,5,10,20,50, None]}

In [62]:
SVC_param = {
                    'penalty' : ['l1','l2'],
                    'dual' : [True,False],
                    'fit_intercept': [True,False],
                    'class_weight' : ['balanced',None],
                    'verbose' :[0],
                    'random_state': [22,None],
                    'max_iter': [10,100,1000]}

In [49]:
grid_decision_tree_5 = GridSearchCV(DecisionTreeClassifier(), decision_tree_param, cv=5) 
start = time() # For working time and tested by cv=5
grid_decision_tree_5.fit(x_train, y_train)
print(f'TIME FOR CV=5 ==> {time() - start}')
print(f'BEST PARAMS FOR GRID DECISION TREE  CV = 5 ==> {grid_decision_tree_5.best_params_}')
print(f'TEST ACC GRID DECISION TREE CV = 5 ==> {grid_decision_tree_5.score(x_test, y_test)}')


TIME FOR CV=5 ==> 19.986003398895264
BEST PARAMS FOR GRID DECISION TREE  CV = 5 ==> {'ccp_alpha': 0.1, 'criterion': 'gini', 'min_samples_leaf': 1, 'min_samples_split': 2, 'random_state': 22}
TEST ACC GRID DECISION TREE CV = 5 ==> 0.6283185840707964


In [61]:
grid_random_forest_5 = GridSearchCV(RandomForestClassifier(), random_forest_param, cv=5) 
start = time() # For working time and tested by cv=5
grid_random_forest_5.fit(x_train, y_train)
print(f'TIME FOR CV=5 ==> {time() - start}')
print(f'BEST PARAMS FOR GRID RANDOM FOREST  CV = 5 ==> {grid_random_forest_5.best_params_}')
print(f'TEST ACC GRID RANGOM FOREST CV = 5 ==> {grid_random_forest_5.score(x_test, y_test)}')

TIME FOR CV=5 ==> 793.1940739154816
BEST PARAMS FOR GRID RANDOM FOREST  CV = 5 ==> {'ccp_alpha': 0.1, 'criterion': 'gini', 'max_depth': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.001, 'n_estimators': 20, 'random_state': 22, 'verbose': 0}
TEST ACC GRID RANGOM FOREST CV = 5 ==> 0.4778761061946903


In [63]:
grid_SVC_5 = GridSearchCV(svm.LinearSVC(), SVC_param, cv=5) 
start = time() # For working time and tested by cv=5
grid_SVC_5.fit(x_train, y_train)
print(f'TIME FOR CV=5 ==> {time() - start}')
print(f'BEST PARAMS FOR GRID SVC  CV = 5 ==> {grid_SVC_5.best_params_}')
print(f'TEST ACC GRID SVC CV = 5 ==> {grid_SVC_5.score(x_test, y_test)}')

TIME FOR CV=5 ==> 153.21070766448975
BEST PARAMS FOR GRID SVC  CV = 5 ==> {'class_weight': 'balanced', 'dual': False, 'fit_intercept': False, 'max_iter': 100, 'penalty': 'l1', 'random_state': 22, 'verbose': 0}
TEST ACC GRID SVC CV = 5 ==> 0.6873156342182891


In [68]:
from sklearn.metrics import accuracy_score  # for testing our optimized model's efficency

In [69]:
sample = grid_SVC_5
sample.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=LinearSVC(),
             param_grid={'class_weight': ['balanced', None],
                         'dual': [True, False], 'fit_intercept': [True, False],
                         'max_iter': [10, 100, 1000], 'penalty': ['l1', 'l2'],
                         'random_state': [22, None], 'verbose': [0]})

In [73]:
sample_1 = grid_decision_tree_5
sample_1.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'ccp_alpha': [0.1, 0.2, 0.5],
                         'criterion': ['chi', 'gini'],
                         'min_samples_leaf': [1, 2, 3, 4, 5],
                         'min_samples_split': [2, 4], 'random_state': [22]})

In [74]:
sample_2 = grid_random_forest_5
sample_2.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'ccp_alpha': [0.1, 0.2, 0.5],
                         'criterion': ['chi', 'gini'],
                         'max_depth': [1, 5, 10, 20, 50, None],
                         'min_samples_split': [2, 4, 6],
                         'min_weight_fraction_leaf': [0.001, 0.1, 0.2, 0.3],
                         'n_estimators': [10, 20, 50, 100],
                         'random_state': [22], 'verbose': [0]})

In [70]:
y_sample = sample.predict(x_test)                                                          
accuracy=(accuracy_score(y_test, y_sample))                        

a=pd.DataFrame([accuracy]);
b=a.max()

print('The Max Value:',b);

The Max Value: 0    0.687316
dtype: float64


In [75]:
y_sample1 = sample_1.predict(x_test)
accuracy=(accuracy_score(y_test, y_sample1))
a=pd.DataFrame([accuracy]);
b=a.max()

print('The Max Value:',b);

The Max Value: 0    0.628319
dtype: float64


In [76]:
y_sample2 = sample_2.predict(x_test)
accuracy = (accuracy_score(y_test, y_sample2))
a=pd.DataFrame([accuracy]);
b=a.max()

print('The Max Value:',b);

The Max Value: 0    0.477876
dtype: float64


In [64]:
from sklearn.metrics import classification_report , confusion_matrix

In [65]:
class_names = ['class 0', 'class 1', 'class 2' , 'class 3']

In [71]:
print(classification_report(y_sample, y_test, target_names=class_names))

              precision    recall  f1-score   support

     class 0       0.85      0.76      0.80       181
     class 1       0.49      0.64      0.55        96
     class 2       0.66      0.52      0.58        52
     class 3       0.58      0.70      0.64        10

    accuracy                           0.69       339
   macro avg       0.65      0.65      0.64       339
weighted avg       0.71      0.69      0.69       339



In [77]:
print(classification_report(y_sample1, y_test, target_names=class_names))

              precision    recall  f1-score   support

     class 0       0.73      0.80      0.77       149
     class 1       0.76      0.49      0.60       190
     class 2       0.00      0.00      0.00         0
     class 3       0.00      0.00      0.00         0

    accuracy                           0.63       339
   macro avg       0.37      0.32      0.34       339
weighted avg       0.75      0.63      0.67       339



In [78]:
print(classification_report(y_sample2, y_test, target_names=class_names))

              precision    recall  f1-score   support

     class 0       1.00      0.48      0.65       339
     class 1       0.00      0.00      0.00         0
     class 2       0.00      0.00      0.00         0
     class 3       0.00      0.00      0.00         0

    accuracy                           0.48       339
   macro avg       0.25      0.12      0.16       339
weighted avg       1.00      0.48      0.65       339



In [72]:
print(confusion_matrix(y_sample, y_test))

[[138  42   1   0]
 [ 23  61  11   1]
 [  1  20  27   4]
 [  0   1   2   7]]


In [79]:
print(confusion_matrix(y_sample1, y_test))

[[119  30   0   0]
 [ 43  94  41  12]
 [  0   0   0   0]
 [  0   0   0   0]]


In [80]:
print(confusion_matrix(y_sample2, y_test))

[[162 124  41  12]
 [  0   0   0   0]
 [  0   0   0   0]
 [  0   0   0   0]]


About Comparization we have three ml algorithms for aimed solution : Random Forest, Decision Tree ,SVC . I applied to three models  for our target and predict colums. Firstly ml algorithms and grid search, also i optimized hyper parameters for each model on grid search. According to grid search results only Random Forest model's accuracy reduced. The remaingins increased after that i applied to all algorithms classification report and confusion matrix